### PR TITLE
replaces float with np.floating

### PR DESCRIPTION
**Pull request by rieder**
possible fix for #202 

Not completely sure if this is the right method, but this seems to work (and gets rid of the warning message) after initial testing.

### CODE REVIEW

**Comment by arjenve** [comment]
please change np.floating to numpy.float 
1) we use "numpy" not "np'
2) " FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`." --> check against numpy.float

**Comment by rieder** [comment]
Oops, I had changed that locally & tested with that but not committed/pushed it to the correct branch...

**Comment by arjenve** [comment]
Still a problem with "floating", that name will be deprecated, the code needs to be "float".

**Comment by rieder** [comment]
so it should be `numpy.float64`?

**Comment by ipelupessy** [comment]
I was under the impression that the proper fix is: float -> numpy.dtype(float).type ??

**Comment by arjenve** [comment]
It is, "numpy.float", I tested this.

So not, "floating" and not "float64", the last one would exclude 32bit floats

**Comment by arjenve** [comment]
Looks good!

**Comment by ipelupessy** [comment]
if its good, lets merge..

**Comment by arjenve** [comment]
Ok, let it be "floating".  Apparently float != floating.

**Comment by ipelupessy** [comment]
can you fix this again in the rieder-patch-float branch?

**Comment by rieder** [comment]
Done

**Pull request merged**
