### PR TITLE
Add FDPS interface

### PR DESCRIPTION
**Pull request by rieder**
Adds an interface for FDPS (as an optional code).
The current interface is only gravitational dynamics (a tree code), but at a later stage also SPH hooks will be added to the interface.
Stopping conditions and get_X_at_point functions are not yet supported.
Hardware acceleration will be added at a later stage.

Some tests are still disabled, because of unimplemented functions. These don't appear essential to me.

### CODE REVIEW

**Comment by ipelupessy** [comment]
it compiles and tests run here, I am ok with merging - but can you add a description somewhere (maybe the docs), or in the source directory, maybe also with the things that still need work?

**Comment by rieder** [comment]
Will do. Not today though. Please wait with merging until I've added that.

**Comment by ipelupessy** [comment]
is this going to be revived at some point??

**Comment by rieder** [comment]
Hmm, something went wrong here - didn't mean to delete that branch. 
Yes, I still intend to revive and finish this - but it'll wait until I can include a more "meaningful" FDPS integrator than the BHTree clone I used from the examples. 
I'll discuss this with @honmaguro and the other FDPS team members.

**Comment by rieder** [comment]
I'm closing this for now - I'll revive this later, when the interface for the 'Pentacle/P3T' implementation of FDPS is complete. That'll be more useful than this current interface (which reproduces BHTree).

**Comment by rieder** [comment]
Re-opening this (but don't merge yet).
The new interface "FDPSSN" is meant to be a "reference" implementation for FDPS-based codes as well as a useful SPH+Nbody code in itself. It works, but the interface is not yet complete (tests are missing, setting parameters is not yet implemented and it does not support parallel execution yet).

**Comment by ipelupessy** [comment]
anywhere near mergeable?

**Comment by rieder** [comment]
Closing this as an interface to FDPS as such isn't needed - an interface to an FDPS-based code exists for PeTar

**Pull request closed without merging**
