### PR TITLE
Add ADS bibcodes to interfaces

### PR DESCRIPTION
**Pull request by rieder**
Work in progress to add ADS bibcodes to all literature references.

### CODE REVIEW

**Comment by rieder** [comment]
This PR aims to improve the literature references in community codes by
1. adding ADS bibcodes to all the references for easier lookup, in the format [bibcode].
2. presenting the references in a common format (to be decided what that should be)

**Comment by spzwart** [comment]
Yes, that is a good idea. I always wanted to make that change, but never got around doing it.
Could we make a central data-repository with all the references and have the read-in by the respective codes, or is it better to keep the ref in the appropriate interface file, where it currently is?

In term of content: what about the ADS bibtex code and the CMDA reference style (which is more complete than the A&A or MNRAS styles.
This PR aims to improve the literature references in community codes by

**Comment by rieder** [comment]
For (2), I am thinking of the following:

```
You have used the following codes, which contain literature references:

	"CodeInterface"
		Author A., Buthor B., [docstring]:
		... "Article Title"
		** Cuthor C., Duthor D., [docstring]:
		... "Article Two Title"
		... Additional comments for Article Two
```

**Comment by rieder** [comment]
Also, there should be literature references for the use of Python and Numpy, and (if used) Matplotlib. And probably some others.

**Comment by rieder** [comment]
And some explanation for the asterisks (** means "citing these articles is not mandatory but recommended", no asterisks means "need to cite these", one asterisk is not defined?)

**Comment by spzwart** [comment]
I was thinking of:

2018araa.book.....P: Portegies Zwart, S., McMillan, S. 2018. Astrophysical Recipes; The art of AMUSE.Astrophysical Recipes; The art of AMUSE.
or
Portegies Zwart, S., McMillan, S. 2018. Astrophysical Recipes; The art of AMUSE.Astrophysical Recipes; The art of AMUSE ( 2018araa.book.....P)

**Comment by rieder** [comment]
> Could we make a central data-repository with all the references and have the read-in by the respective codes, or is it better to keep the ref in the appropriate interface file, where it currently is?

I prefer to keep it local, since we are making AMUSE more modular and a centralised citation library would not help with that.

> In term of content: what about the ADS bibtex code and the CMDA reference style (which is more complete than the A&A or MNRAS styles.

> I was thinking of: 2018araa.book.....P: Portegies Zwart, S., McMillan, S. 2018. Astrophysical Recipes; The art of AMUSE.Astrophysical Recipes; The art of AMUSE. or Portegies Zwart, S., McMillan, S. 2018. Astrophysical Recipes; The art of AMUSE.Astrophysical Recipes; The art of AMUSE ( 2018araa.book.....P)

That's fine with me, but I think I would prefer multiple lines for increased readability. I think I would favour the docstring at the beginning of the line (easier to find, since it doesn't move around).

**Comment by rieder** [comment]
We could move the references to a "references.txt" file (or something) for each community code though. That would be more accessible than the current method of parsing the docstring (since no one knows exactly how this parsing is done).

**Comment by rieder** [comment]
That would have other benefits: we could use a documentation standard (e.g. bibfiles, or something more recent/advanced), and just parse these for output and/or provide a bibfile that AMUSErs can just include in their paper directly. Perhaps similar to the "reproducible paper" method from Akhlaghi.

**Comment by spzwart** [comment]
Yes, enter the entire bibtex blurb is probably best.
What about adding a file called: interface.bib
or -codename.bib-
These could be included directly in any latex document.

**Comment by rieder** [comment]
Yes, "interface.bib" is probably the easiest way to do this. One caveat is that we would have to process the file as well, which adds some dependencies to AMUSE... Not sure how to do this yet (I don't want TeXLive as a dependency for AMUSE ;) ).

**Comment by rieder** [comment]
@ipelupessy If I remember correctly you created an issue about something related to this a year ago or so... About some documentation format? I forgot exactly what it was and can't find it...

**Comment by ipelupessy** [comment]
hmmm, does not directly ring a bell...I think adding the ADS codes is fine and enough for the moment...

**Comment by rieder** [comment]
I was thinking of issue #232 (which is something different than this after all).

**Comment by ipelupessy** [comment]
is probably ok to merge?

**Comment by rieder** [comment]
This one isn't "done", but it's an improvement already so I'm merging it.

**Pull request merged**
