### PR TITLE
Make textbook and other examples python3 compatible

### PR DESCRIPTION
**Pull request by rieder**
This patch makes all textbook examples python3 compatible.

Replaces print statements by print functions everywhere, and a few other fixes where required.
The examples are still python2 compatible.

### CODE REVIEW

**Comment by rieder** [comment]
Pull request makes textbook, application and syllabus examples work with python3.

**Comment by rieder** [comment]
@spzwart @stevemcmillan @arjenve Can I merge these changes? 99% of it is replacing `print X` with `print(X)` and `map(X)` with `list(map(X))`, but even the few other changes shouldn't block the scripts from working in python2 (I tested where I had doubts).

**Comment by rieder** [comment]
@spzwart @arjenve @stevemcmillan Any objections to me merging this?

**Comment by arjenve** [comment]
I'll review the code! (probably tomorrow or on Wednesday)

**Comment by rieder** [comment]
Great, thanks!

**Comment by rieder** [comment]
This is also a partial fix for #250

**Comment by rieder** [comment]
May need to double check if these examples need to import print_function or not...

**Comment by rieder** [comment]
OK, brought this branch up-to-date with Python3 branch

**Comment by rieder** [comment]
I would like to fix the issues in #533 before merging this

**Comment by ipelupessy** [comment]
can this be merged?

**Comment by rieder** [comment]
Yes, will do. #533 is not fully solved yet, but I think the rest isn't Py3 specific.

**Comment by ipelupessy** [comment]
ok, so I made a python2 branch..and the PR for merging python3...

**Pull request merged**
