### PR TITLE
Updated macOS install instructions for macports.

### PR DESCRIPTION
**Pull request by rieder**
Removed many details that are no longer necessary, or outdated.
Updated to most recent gcc version

### CODE REVIEW

**Comment by arjenve** [comment]
Steven,  Thank you for this update!! 

As for gcc7, I do not want to put this as the standard option for AMUSE, it has multiple issues (some optimizations are dubious and C++ does thing subtly different). 
So could you please keep the variants to gcc49 and refer to gcc7 / gcc6 where the options are discussed?

**Comment by rieder** [comment]
Ok, I’ll make that change. 

By the way, I was working on installing Amuse with Python3 today, I made a page for that as well on my Amuse github wiki (https://github.com/rieder/amuse/wiki/Installation-on-macOS-with-Python3). I use virtualenv for this install, it seems to work quite well (some issues with nosetests).

**Comment by rieder** [comment]
Ok, I've changed the default back to gcc 4.9. 
As a sidenote, recent versions of Ubuntu and Debian no longer have packages for gcc versions lower than 6, so we should make sure these recent GCC versions work correctly with Amuse.

**Comment by rieder** [comment]
@arjenve OK to merge?

**Comment by arjenve** [comment]
Yes, Will do!

**Pull request merged**
