### PR TITLE
fix gravitational dynamics state for set_mass etc

### PR DESCRIPTION
**Pull request by ipelupessy**

### CODE REVIEW

**Comment by ipelupessy** [comment]
needs tested against all gd codes

**Comment by rieder** [comment]
This solves the problem with BHTree for me.

**Comment by rieder** [comment]
perhaps also set_radius should be included?

**Comment by ipelupessy** [comment]
have you tried other codes? though I think if it breaks any of the other codes, these are at fault...

**Comment by rieder** [comment]
> have you tried other codes? though I think if it breaks any of the other codes, these are at fault...

ph4 seems fine, I have not yet tried others (will do so later). I agree this should work and if it doesn't the other codes are at fault.

**Comment by ipelupessy** [comment]
merge?

**Comment by rieder** [comment]
I'll run the tests for the other gravity codes, if they run OK I'll merge.

**Comment by rieder** [comment]
All tests I ran passed - merging.

**Pull request merged**
