### PR TITLE
Pre-requisites installation for Ubuntu updated

### PR DESCRIPTION
**Pull request by sr6033**
The pre-requisites installation including mpich2 has been updated as per the libraries available in official sites.

### CODE REVIEW

**Comment by ipelupessy** [comment]
thanks! maybe an ubuntu  version number should be added for the new intstructions (I think the older instructions would work for anything pre 2016 or so?). furthermore: do you know why its necessary now to install mpich2 by hand?? (and do you know if the openmpi instructions still work?)

**Comment by sr6033** [comment]
The installation instruction that I have added will work for any new versions of **Ubuntu(15 or above)**. I cannot say about the working of older instructions for previous Ubuntu versions because I haven't tested those on older versions. 

**mpich2** is not available in the official Ubuntu repos list. I faced this issue while trying to install it via apt-get. That is why it has to be installed manually now.

There is another issue that newer versions of mpich2(specifically 1.3 & above) doesn't have **mpd** anymore. That is the reason I have recommended to download mpich2 ver 1.2 which is an older version. If your instructions of **Amuse** can be changed from **mpd** then new versions will work.

**Comment by arjenve** [comment]
Yes, the latest version of mpich in UBUNTU should be fine  (mpich 3.x is known to work).

We do not depend on mpd,  starting scripts without mpd (hydra is now the default) requires the mpiexec command:

mpiexec python <script.py>

So yes, mpich should be used as is from the ubuntu repository...

**Comment by ipelupessy** [comment]
does the package name "mpich" in that case work?

**Comment by sr6033** [comment]
If the official **mpich** is working then the instructions here: http://www.amusecode.org/doc/install/howto-install-AMUSE.html
 need to be updated as per Hydra.

**Comment by ipelupessy** [comment]
thanks, that page should indeed be updated since mpd is now no longer supported I think (though there was info on the hydra manager, but this should be mentioned first as the default)..I think the prerequisite page for ubuntu still needs some updates..didn't have a chance to test it yet...

**Comment by ipelupessy** [comment]
commit 7a576a2 fixes this now

**Pull request closed without merging**
