### PR TITLE
AMUSE singularity definition file

### PR DESCRIPTION
**Pull request by ll4strw**
I reckon it could be useful.

### CODE REVIEW

**Comment by ipelupessy** [comment]
ok, thanks! we had some previous experiments with singularity recipes, do you rememebr why we did or didn't add a recipe before @rieder ? 

in any case: often the definition file is just called Singularity - is there a reason not to do so?

**Comment by ll4strw** [comment]
The name can be changed as you wish.

**Comment by ipelupessy** [comment]
There is a seperate repository now, so maybe can close?

**Comment by ipelupessy** [comment]
close due to seperate repo

**Pull request closed without merging**
