### PR TITLE
Support HDF5 compression of AMUSE files

### PR DESCRIPTION
**Pull request by rieder**
use with 'compression=True' or 'compression="gzip", compression_opts=compression_level'
(compression level is a number up to 9)

### CODE REVIEW

**Comment by rieder** [comment]
```
In [1]: from amuse.lab import *
   ...: stars = new_plummer_model(1000000)
   ...: write_set_to_file(stars, 'plummer.amuse', compression_opts=None)
   ...: write_set_to_file(stars, 'plummer.amuse_gzip', compression='gzip')
   ...: write_set_to_file(stars, 'plummer.amuse_uncomp', compression=None, compression_opts=None)
   ...: write_set_to_file(stars, 'plummer.amuse_gzip5', compression='gzip', compression_opts=5)
   ...: write_set_to_file(stars, 'plummer.amuse_gzip9', compression='gzip', compression_opts=9)

In [2]: !ls -ltr plummer.amuse*
-rw-r--r-- 1 rieder staff 72164248 25 mrt 16:21 plummer.amuse
-rw-r--r-- 1 rieder staff 54211839 25 mrt 16:21 plummer.amuse_gzip
-rw-r--r-- 1 rieder staff 72012784 25 mrt 16:21 plummer.amuse_uncomp
-rw-r--r-- 1 rieder staff 54211839 25 mrt 16:21 plummer.amuse_gzip5
-rw-r--r-- 1 rieder staff 54211839 25 mrt 16:21 plummer.amuse_gzip9
```

**Comment by rieder** [comment]
compression level doesn't seem to do much, but compression seems to shave off about 50% of the file size at the cost of speed (as could be expected for gzip compression).

**Comment by ipelupessy** [comment]
so does this automatically detect compression in a previous saved file?

**Comment by ipelupessy** [comment]
its already worthwhile if the compression works to shrink arrays with limited information (ie equal mass, coordinates that are the same across columns etc)

**Comment by rieder** [comment]
yes! It's transparent when opening a file.

**Comment by rieder** [comment]
(at least in AMUSE and when using h5py)

**Comment by ipelupessy** [comment]
- I think the PR needs tests
- if its really transparent we may consider making it the default

**Comment by rieder** [comment]
a reason for not making it the default could be that it's definitely slower.
I will add tests.

**Comment by ipelupessy** [comment]
ok, that is good reason; you could also add a store tyoe ('hdf5.gz' or something) as alias for the options as an alternative..

**Comment by rieder** [comment]
I think "compression=True" is a very clear keyword :). I think it suffices.

**Comment by rieder** [comment]
@ipelupessy I put a FIXME in line 105 of store_v2.py, since I thought this was a bit odd:
```
            dtype = numpy.asanyarray(input).dtype
            if dtype.kind == 'U':
                new_dtype = numpy.dtype('S' + dtype.itemsize * 4)
                dataset = group.create_dataset(
                    name,
                    shape=shape,
                    dtype=dtype,  # FIXME new_dtype?
```
I think either this should be `dtype=new_dtype` or we could scrap the new_dtype line.

**Comment by rieder** [comment]
(this is not directly related to this PR, but just something I noticed)

**Comment by ipelupessy** [comment]
hmm, can you see if this is old or added at some point (to maintain compatibility, or for python 2->3??)
there shouldn;t be a reason to have different dtype (hdf5 should accept numpy dtypes)

**Comment by rieder** [comment]
It seems to date back 6 years, related to #24. But clearly it wasn't needed so I'll remove the new_dtype line.

**Comment by ipelupessy** [comment]
yea, the case it catches  should be in a test anyways

**Comment by rieder** [comment]
ok to merge?

**Comment by ipelupessy** [comment]
should be ok

**Pull request merged**
