### PR TITLE
Allowed evolution to and synchronization at a specified time (not nec…

### PR DESCRIPTION
**Pull request by stevemcmillan**
…essarily

a natural time step).

### CODE REVIEW

**Comment by ipelupessy** [comment]
is it possible to add a test case

**Comment by stevemcmillan** [comment]
Script test_sync.py illustrates use. I implemented force_sync as a parameter, mainly because I don't know how to add an argument to evolve_model(). If someone can do it better, please do.

**Comment by ipelupessy** [comment]
force_sync as parameter is ok (actually preferred)

**Comment by stevemcmillan** [comment]
Has this been merged into amusebase yet? Josh needs to use it with Flash.

**Pull request merged**
