### PR TITLE
adding option to SeBa to retrieve zeta_thermal & zeta_adiabatic from …

### PR DESCRIPTION
**Pull request by silviatoonen**
…within AMUSE

### CODE REVIEW

**Comment by rieder** [comment]
I have one failed test, seems to be due to changed results in SeBa:
```
==================================================== FAILURES ====================================================
___________________________________ TestSeBa.test_add_stars_at_different_times ___________________________________

self = <amuse.test.suite.codes_tests.test_seba.TestSeBa testMethod=test_add_stars_at_different_times>

    def test_add_stars_at_different_times(self):
        instance = self.new_instance_of_an_optional_code(SeBa)
        stars = Particles(2)
        stars[0].mass = 10.0 | units.MSun
        stars[1].mass = 9 | units.MSun

        instance.particles.add_particles(stars)
        instance.evolve_model(30|units.Myr)

        self.assertAlmostRelativeEquals(instance.particles.age, [30,30] |units.Myr)
        self.assertAlmostRelativeEquals(instance.model_time, 30 | units.Myr)
        self.assertAlmostRelativeEquals(instance.particles[0].mass, 1.2507 | units.MSun, 4)
>       self.assertAlmostRelativeEquals(instance.particles[1].mass, 8.9340 | units.MSun, 4)

test_seba.py:532:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../amusetest.py:140: in failUnlessAlmostRelativeEqual
    self._raise_exceptions_if_any(failures, first, second, "{0!r} != {1!r} within {2!r} places", msg, places)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <amuse.test.suite.codes_tests.test_seba.TestSeBa testMethod=test_add_stars_at_different_times>
failures = array([ True], dtype=bool), first = quantity<8.93512330716 MSun>, second = quantity<8.934 MSun>
err_fmt_string = '{0!r} != {1!r} within {2!r} places', msg = None, args = (4,)

    def _raise_exceptions_if_any(self, failures, first, second, err_fmt_string, msg, *args):
        if len(failures) == 1:
            if failures[0]:
>               raise self.failureException(msg or err_fmt_string.format(first, second, *args))
E               AssertionError: quantity<8.93512330716 MSun> != quantity<8.934 MSun> within 4 places

../../amusetest.py:73: AssertionError
============================================ short test summary info =============================================
FAILED test_seba.py::TestSeBa::test_add_stars_at_different_times - AssertionError: quantity<8.93512330716 MSun>...
========================================== 1 failed, 21 passed in 4.24s ==========================================
```
Could you update the test to reflect this change?

**Comment by silviatoonen** [comment]
Hi Steven,
No problem updating it, however the value given by the error message is weird.
If I run a 9Msun star with SeBa on my computer I get a mass of 8.93144 after 30 Myr. The test expects a value of 8.9340, where as according to the error message it should be 8.9351.
My version of SeBa is the most up to date one, the one I'm trying to change the amuse version to as well. Can you double check it on your end as well? When I run the tests on my computer I get no failed tests.
Cheers Silvia


---------------------------------------------------------------------
Dr. Silvia Toonen
Assistant professor
Anton Pannekoek Institute
University of Amsterdam
Email:  ***@***.******@***.***>
***@***.******@***.***> will soon be deactivated.
Website: https://staff.fnwi.uva.nl/s.g.m.toonen/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaff.fnwi.uva.nl%2Fs.g.m.toonen%2F&data=04%7C01%7Cservicedesk-icts%40uva.nl%7Ce2bdbbd0a70043e9f36f08d8ccef8185%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637484676327089939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=89YxQBjtPoJ%2BC3gAfS9IC6HGNPTNQPeMg47HQL0UMoo%3D&reserved=0>
---------------------------------------------------------------------
________________________________

**Comment by rieder** [comment]
Hi Silvia,

I get:
```python
In [1]: from amuse.lab import *

In [2]: instance = Seba()

In [3]: stars = Particles(2)
   ...: stars[0].mass = 10.0 | units.MSun
   ...: stars[1].mass = 9 | units.MSun
   ...:
   ...: instance.particles.add_particles(stars)
   ...: instance.evolve_model(30 | units.Myr)
Out[3]: []

In [4]: print(instance.particles.mass)
[1.25072398252, 8.93512330716] MSun
```
This is using the SeBa version with git hash `edd5b13460b469bc9a994018071440718d7d3fd6`.

**Comment by rieder** [comment]
(of note: we should find a way add the git hash/version of the worker to the interface for easy checking which version we're using!)

**Comment by rieder** [comment]
> (of note: we should find a way add the git hash/version of the worker to the interface for easy checking which version we're using!)

Already exists to a degree: 
```print(instance.version())
2022.6.4.dev100+g3bb37f00d
```

**Comment by silviatoonen** [comment]
I've done a make distclean, followed by make to make a new SeBa worker. I have acess to the zeta parameters now through amuse, however the mass of a 9Msun star after 30Myr is still the same value as I had before: 8.93144Msun.
I've also ran the amusetest.py and do not receive an error message ...


---------------------------------------------------------------------
Dr. Silvia Toonen
Assistant professor
Anton Pannekoek Institute
University of Amsterdam
Email:  ***@***.******@***.***>
***@***.******@***.***> will soon be deactivated.
Website: https://staff.fnwi.uva.nl/s.g.m.toonen/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaff.fnwi.uva.nl%2Fs.g.m.toonen%2F&data=04%7C01%7Cservicedesk-icts%40uva.nl%7Ce2bdbbd0a70043e9f36f08d8ccef8185%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637484676327089939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=89YxQBjtPoJ%2BC3gAfS9IC6HGNPTNQPeMg47HQL0UMoo%3D&reserved=0>
---------------------------------------------------------------------
________________________________

**Comment by rieder** [comment]
Very odd... 
I just tried again, with a clean installation from this AMUSE branch, and I still get the same error (8.93512330716 MSun).
Maybe we can have a look together later this week?

**Comment by rieder** [comment]
For reference, the discrepancy in mass was caused by evolving the stars as a binary vs evolving them as single stars.

**Pull request closed without merging**
