### PR TITLE
Initial commit of SecularMultiple (Adrian Hamers)

### PR DESCRIPTION
**Pull request by maxwelltsai**
Initial commit of the SecularMultiple interface (author: Adrian
Hamers). Code paper: http://adsabs.harvard.edu/abs/2016MNRAS.459.2827H

### CODE REVIEW

**Comment by ipelupessy** [comment]
I think it needs tests..

**Comment by ipelupessy** [comment]
maybe Adrian has a test or an example which can be easily converted to a test...

**Comment by maxwelltsai** [comment]
@ipelupessy I have a test script from Adrian. Where should I put it? Maybe under examples/application?

**Comment by maxwelltsai** [comment]
Good, thanks!

2017-01-13 16:56 GMT+01:00 ipelupessy <notifications@github.com>:

**Comment by ipelupessy** [comment]
hmm, not working here...but that could be something on my machine...

**Pull request merged**
