### PR TITLE
Update SeBa version

### PR DESCRIPTION
**Pull request by silviatoonen**
SeBa now includes the possibility for chemically homogeneous evolution  
seba tests checked and succesfully passed

### CODE REVIEW

**Comment by silviatoonen** [comment]
seba tests checked and succesfully passed

**Comment by rieder** [comment]
Could you add a test for this option as well?

**Comment by silviatoonen** [comment]
Not really. CHEM is not used by default. So the typical Amuse user would not use it.
CHEM only switches on in SeBa if one goes into the code and flips a flag. So no need to add a test.


---------------------------------------------------------------------
Dr. Silvia Toonen
Assistant professor
Anton Pannekoek Institute
University of Amsterdam
Email:  ***@***.******@***.***>
***@***.******@***.***> will soon be deactivated.
Website: https://staff.fnwi.uva.nl/s.g.m.toonen/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaff.fnwi.uva.nl%2Fs.g.m.toonen%2F&data=04%7C01%7Cservicedesk-icts%40uva.nl%7Ce2bdbbd0a70043e9f36f08d8ccef8185%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637484676327089939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=89YxQBjtPoJ%2BC3gAfS9IC6HGNPTNQPeMg47HQL0UMoo%3D&reserved=0>
---------------------------------------------------------------------
________________________________

**Comment by rieder** [comment]
ok

**Review by rieder — APPROVED** [review]

**Pull request merged**
