### PR TITLE
added citation metadata

### PR DESCRIPTION
**Pull request by jspaaks**
Hi @ipelupessy,

this PR adds a CITATION.cff metadata file for citation. I then used ``cffconvert`` from PyPI to generate a ``.zenodo.json`` from it, such that we can tell Zenodo about the metadata we want to associate with each release.

The set of authors in CITATION.cff needs checking, in order to determine we included the correct people. I don't know if you want to include all commiters as well, although I feel including them is a token of appreciation for their work. BTW I used the order given here https://github.com/amusecode/amuse/graphs/contributors to determine the order the authors should be in.

Also, please check the orcids and affiliations (i just did a superficial search which hopefully led me to the right people, but it's worth checking.)

Finally, the metadata assumes that there will be another (pre)release ...today. I've labeled it ``11.3`` to be consistent with your naming scheme.

Let me know if I can help with anything,
-Jurriaan

### CODE REVIEW

**Comment by ipelupessy** [comment]
ok, thanks! I did notice that the autogenerated authorlist was not good....I think we do want to change the order , my proposal would be:
Portegies Zwart, van Elteren, Pelupessy, McMillan etc
and also a lot of authors of contributing packages are not included (since committed themselves), we are still thinking how to solve this...

**Comment by rieder** [comment]
I think the author list is (mostly) OK for the "core" AMUSE, but indeed not for the current, "full" AMUSE distribution.

**Comment by ipelupessy** [comment]
ok, will also check the old svn committers (e.g. Nathan, Marcell should also be on it)...in any case: what is the convention for the affiliation: is it the current or the one when contributing?

**Comment by jspaaks** [comment]
Good question, i would think it's the one while contributing.

**Comment by ipelupessy** [comment]
the git log gives around 70 committers (with some duplicates)..

**Comment by jspaaks** [comment]
@ipelupessy BTW theres no need to write the ``.zenodo.json`` file by hand, just use ``cffconvert`` from PyPI:
```bash
pip install --user cffconvert
cd thedirthathasacitation.cff
cffconvert -f zenodo -ig > .zenodo.json # but the description section likely needs editing, cffconvert is a bit overenthusiastic when it comes to escaping characters
```

**Comment by spzwart** [comment]
Ok like the idea of a credit section.

there are so many people contributing, even without knowing, but just by 
making their codes available. I think that they deserve some credit too.

**Comment by ipelupessy** [comment]
I have added a few more people; its still a bit arbitrary, but I have added those
committer which have more than 10 commits and/or who have had significant  contribution
when (long time) working with AMUSE

**Comment by ipelupessy** [comment]
this would leave e.g. authors of the community codes (whom may not even be aware of their code being included) for the credits section (this could be tens or hundreds of people)

**Comment by ipelupessy** [comment]
btw, who was svn user "punzo" ??

**Comment by rieder** [comment]
Davide?

**Pull request merged**
