### PR TITLE
Rebound changes: add support for softening and for setting boundary types (only for some integrators)

### PR DESCRIPTION
**Pull request by rieder**

### CODE REVIEW

**Comment by ipelupessy** [comment]
do you know what the end_time_accuracy_factor in the test_rebound.py is??

**Comment by rieder** [comment]
Not sure - could it be related to exact_finish_time ("set to 1 to finish the integration exactly at model_time. Set to 0 to finish at the next dt")? That one is currently hard-set to 1, but I changed it in my working branch to a proper parameter.

**Comment by ipelupessy** [comment]
I think if it is possible to finish at the exact time this is preferable (spec of AMUSE is to finish at end_time or later), so I don't think this parameter is necessary..but then the paramter exact_finish_time should always be 1 (and end_time_accuracy_factor removed from the test)...

**Comment by rieder** [comment]
Well, I added it for testing purposes (was getting weird timestep problems, but I think Arjen solved that problem now). It's an optional parameter in Rebound itself. I agree, end_time_accuracy_factor seems to have purpose to me and should be removed if that is indeed so.

**Comment by ipelupessy** [comment]
ok, i have removed end_time_accuracy_factor from the test (just to double check: it was not defined in interface.py of master)

**Comment by arjenve** [comment]
It's a parameter in Hermite (the test may have come from that), it is used to stop the simulation just before, exactly on or just after the given time in evolve_model. (it is now only in Hermite, as an "experimental" feature).

**Pull request merged**
