### PR TITLE
2to3 test/

### PR DESCRIPTION
**Pull request by rieder**

### CODE REVIEW

**Comment by ipelupessy** [comment]
is it possible to break this down in:
- assert replacements and prints
- and other stuff
and maybe ignore/ disable list around .values()..I have got the feeling this should work ok automatically

(there might not be much diff left after the this)

**Comment by ipelupessy** [comment]
(this for the actual tests, not for the code in src/amuse/test)

**Comment by rieder** [comment]
> (this for the actual tests, not for the code in src/amuse/test)

I included those later...

**Comment by rieder** [comment]
> is it possible to break this down in:
> 
> * assert replacements and prints
> * and other stuff
>   and maybe ignore/ disable list around .values()..I have got the feeling this should work ok automatically
> 
> (there might not be much diff left after the this)

Sure, but I'll wait for Travis to finish checking this one first.

**Comment by ipelupessy** [comment]
there are failures, osx reports as passed, but also has errors...
nothing overly serious though

**Comment by rieder** [comment]
I created a separate PR for print+asserts changes, need to make a third one which re-applies the other changes onto that PR... This is a bit tricky, will do it later.

**Comment by ipelupessy** [comment]
closing this one...

**Pull request closed without merging**
