### PR TITLE
Add bool to converted dtypes, fix typo

### LINKED ISSUE #228: Creating sphinx documentation fails because of missing 'bool' dtype conversion
Creating documentation currently fails for me with the following exception:

```
Exception occurred:
  File "/Users/rieder/Code/Amuse/src/amuse/rfi/tools/create_definition.py", line 273, in start
    typestring = self.dtype_to_ctype[parameter.datatype]
KeyError: 'bool'
```

### PR DESCRIPTION
**Pull request by rieder**
- Adds conversion to fortrantype and ctype for 'bool' dtype (fixes #228)
- Renames 'fortantype' to 'fortrantype'

### CODE REVIEW

**Comment by rieder** [comment]
@arjenve is this an OK solution?
It seems the documentation fails to build because of this problem, and I think this has been the case for a while (at least some previous edits I made to the documentation haven't shown up on the Amusecode.org website yet)...

**Comment by ipelupessy** [comment]
I think documentation is rebuild is triggered manually ( @arjenve ?)

**Comment by rieder** [comment]
Ok to merge though? For me, this patch is necessary to build docs...

**Comment by ipelupessy** [comment]
will merge, strangely enough the buildbot builds the doc ok, so I will keep an eye..

**Comment by rieder** [comment]
Thanks

**Pull request merged**
