### PR TITLE
Bugfix issue for #850

### PR DESCRIPTION
**Pull request by rieder**
- [x] Test issue 850
- [x] Add test to workflow for this branch
- [ ] Fix issue
- [ ] Remove workflow
- [ ] Merge & Remove branch

### CODE REVIEW

**Comment by rieder** [comment]
The test_issue_850 workflow tests issue #850 - it currently fails so the bug is still there (of course, since no fix has been made yet).
I'm not sure what causes the issue, but it is clear that SeBa does not evolve star[1] from the test if a binary of stars[0,2] is added. Not sure if this extends to SeBa only evolving stars that are also in a binary (if any binary is added), perhaps also add this to the test?
(cc @silviatoonen)

**Comment by ipelupessy** [comment]
see comment i made in #850

**Comment by ipelupessy** [comment]
this can be fixed see the comment on #850

**Comment by silviatoonen** [comment]
Hi all,
this goes above my knowledge of amuse - if the suggestion of Inti works, let's go ahead and implement it.
Otherwise, Simon would be the best person, knowing amuse & SeBa both?
Cheers Silvia


---------------------------------------------------------------------
Dr. Silvia Toonen
Assistant professor
Anton Pannekoek Institute
University of Amsterdam
Email:  ***@***.******@***.***>
***@***.******@***.***> will soon be deactivated.
Website: https://staff.fnwi.uva.nl/s.g.m.toonen/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaff.fnwi.uva.nl%2Fs.g.m.toonen%2F&data=04%7C01%7Cservicedesk-icts%40uva.nl%7Ce2bdbbd0a70043e9f36f08d8ccef8185%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637484676327089939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=89YxQBjtPoJ%2BC3gAfS9IC6HGNPTNQPeMg47HQL0UMoo%3D&reserved=0>
---------------------------------------------------------------------
________________________________

**Comment by ipelupessy** [comment]
if the test cases are ok, its prob ok

**Comment by rieder** [comment]
Test is successful, so are the regular SeBa tests. Merging.

**Comment by silviatoonen** [comment]
thanks!

---------------------------------------------------------------------
Dr. Silvia Toonen
Assistant professor
Anton Pannekoek Institute
University of Amsterdam
Email:  ***@***.******@***.***>
***@***.******@***.***> will soon be deactivated.
Website: https://staff.fnwi.uva.nl/s.g.m.toonen/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaff.fnwi.uva.nl%2Fs.g.m.toonen%2F&data=04%7C01%7Cservicedesk-icts%40uva.nl%7Ce2bdbbd0a70043e9f36f08d8ccef8185%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637484676327089939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=89YxQBjtPoJ%2BC3gAfS9IC6HGNPTNQPeMg47HQL0UMoo%3D&reserved=0>
---------------------------------------------------------------------
________________________________

**Pull request merged**
