### PR TITLE
make mpi optional for amuse-framework

### PR DESCRIPTION
**Pull request by ipelupessy**
this needs to be tested

### CODE REVIEW

**Comment by ipelupessy** [comment]
it would be nice to have amusifier report what MPI functionality the installation has...

**Comment by ipelupessy** [comment]
now only amuse-framework has the option of being pip installed w/o mpi4py...

**Comment by ipelupessy** [comment]
ok, I don't think we need codecov report here!!

**Comment by rieder** [comment]
No that seems a bit much...

**Comment by ipelupessy** [comment]
I think this PR might actually work...

**Comment by ipelupessy** [comment]
but it is nice that codecov works..I looked at the report and it reports detailed info, can be very handy

**Comment by rieder** [comment]
yes I think so too. I've now disabled the comments, but it'll still work.

**Pull request merged**
