### PR TITLE
MOBSE & MOSSE: pull request

### PR DESCRIPTION
**Pull request by GiacobboNicola**

### CODE REVIEW

**Comment by arjenve** [comment]
Thank you for the pull request,  A few small comments:

* Some binaries are in the pull request, could you do a 'make clean'  / remove the binaries? (mobse_worker, mobse_worker.dSym directory, src/mobse, src/mobse.dSym)
* Some temporary (editor?) hidden files are also in there for example src/_.star.f.
* Some mac files '.DS_Store'

**Comment by GiacobboNicola** [comment]
Dear Arijen, 

Sorry I have not noticed them.

I do it soon.

Nicola Giacobbo

**Comment by rieder** [comment]
@GiacobboNicola I've submitted a pull request to your branch to include code tests for SSE and BSE. Could you review these before we merge this?

**Comment by GiacobboNicola** [comment]
@rieder Of course I can. I'll do as soon as possible.

**Comment by rieder** [comment]
Thanks. The SSE/BSE tests currently fail in a few cases when I adapt them for MOSSE/MOBSE, in most cases because the result differs from what SSE/BSE would give (which is to be expected), but in a few cases it is because of some other error (probably due to interface differences between MOSSE/SSE and MOBSE/BSE).

**Comment by GiacobboNicola** [comment]
You can find a test file (for MOBSE) in its own community directory. It should work. Let me know if you have problem even with that.

**Comment by rieder** [comment]
Looks fine now. Merging.

**Pull request merged**
