### PR TITLE
Replace 'object' with 'handler' where object was not a Python object

### PR DESCRIPTION
**Pull request by rieder**
Patch for #305, replacing 'object' with 'handler' in places where we should not be using 'object'.
Work in progress.

### CODE REVIEW

**Comment by rieder** [comment]
Any more places where this should be replaced?

**Comment by ipelupessy** [comment]
I think these pattern should be safe to replace:
define_.*object.* 
object.add_.*
object.ERROR_CODE
object.INDEX
object.NO_UNIT

also: some logging wip seems to have slipped in

**Comment by ipelupessy** [comment]
the travis tests do not yet cover the code interfaces..you have to test this locally

**Comment by rieder** [comment]
> I think there a little bit too many replacements, cases when object occurs in the class definition ( and maybe other uses) should not be replaced, ie
> 
> ```
> class FastKickDoc(handler):
> ```
> is wrong.

This one slipped through, but I think I got them elsewhere... I tried to pay attention to that.

**Comment by rieder** [comment]
> also: some logging wip seems to have slipped in

Ah, yes. Was clearly not the intention, I'll undo that.

**Comment by ipelupessy** [comment]
think its good to go..any errors or typos should surface quickly..

**Comment by rieder** [comment]
Agreed. I will merge it then.

**Pull request merged**
