### PR TITLE
add package for tests

### PR DESCRIPTION
**Pull request by ipelupessy**
this package should include all the tests

user can then:
nosetests amuse.test.suite

issues:
currently it has amuse as prereq. maybe better idea to allow partial installs to be tested (or include tests in the respective packages...)

### CODE REVIEW

**Comment by ipelupessy** [comment]
now it depends on amuse-framework and installs all tests - I think that is ok..

main issue is the fact that it generates a lot of test output and build files in the cwd..not nice..

**Comment by rieder** [comment]
Do the tests really need to create permanent output?  Maybe just put it in a tempdir?

**Comment by rieder** [comment]
I think this package is fine for now, but I think in the long term it would be better to package code-tests with their respective code.

**Comment by rieder** [comment]
Still, there will be a need for non-code-specific tests and tests that depend on multiple codes, so this package should exist.

**Comment by ipelupessy** [comment]
yea, I think for now its ok. its use would be for debugging: if an issue crops up you can just install all test and run only the ones you need..

**Comment by rieder** [comment]
Ok - I've uploaded it to PyPI now.

**Pull request merged**
