### PR TITLE
merge python3 to master

### PR DESCRIPTION
**Pull request by ipelupessy**
open for comment...

ther eare a bunch of open issues for python3:
https://github.com/amusecode/amuse/projects/3
nothing overtly important...

### CODE REVIEW

**Comment by rieder** [comment]
NB: I have been running on this branch for a while now myself and we've fixed all the issues I encountered during this time. So unless others will also test it I expect we won't find any new issues.

**Comment by ipelupessy** [comment]
I have made the python2 branch..I think the merge does not need to coincide with a release..let me know whenever you think its good to merge..

**Comment by rieder** [comment]
I see nothing that should block a merge at this point. I'm happy for it to be merged.

**Comment by rieder** [comment]
I'll draft an announcement email.

**Pull request merged**
