### PR TITLE
Syntax cleanup (no tabs, other pep8-compliance)

### PR DESCRIPTION
**Pull request by rieder**
Only syntax changes in this PR

### CODE REVIEW

**Comment by ipelupessy** [comment]
this one is for simon or steve to decide (textbook)...

**Comment by rieder** [comment]
Yes - I discussed this with Steve at the MIDAS meeting.

**Comment by ipelupessy** [comment]
status?

**Comment by rieder** [comment]
haven't heard - but I see no harm in these changes (except some conflicts need resolving by now). @spzwart and/or @stevemcmillan: will you leave it to our discretion to merge this? :)

**Comment by ipelupessy** [comment]
closing because needs to be redone for python 3

**Pull request closed without merging**
