### PR TITLE
2to3 conversion of rfi/

### PR DESCRIPTION
**Pull request by rieder**
Initial automatic conversion. Need to check for ugly constructions etc., but this code is essentially what AMUSE-12 currently looks like under Python 3.

### CODE REVIEW

**Comment by rieder** [comment]
> just to be sure - this is what setup.py generates in the build directory with python setup.py build?

Yes, the files are identical.

**Comment by ipelupessy** [comment]
I think the changes I have made are safe...

**Comment by ipelupessy** [comment]
I am scratching my head currently on the iteritems -> items and replacement with keys (there are AMUSE classes which implement these...) So I am not sure the auto 2-->3 changes work in these cases (the heuristics for the changes may get it wrong?)

**Comment by rieder** [comment]
well, it should /work/ (because it's tested with AMUSE 12), but not sure it's how we want it to be.  Let's discuss tomorrow?

**Comment by ipelupessy** [comment]
I think we can just be optimistic, because if it fails it gives quite clear error...

**Pull request merged**
