### PR TITLE
Update Ubuntu installation doc (redo #211)

### PR DESCRIPTION
**Pull request by ipelupessy**
rebased #211

### CODE REVIEW

**Comment by ipelupessy** [comment]
Package names have changed very slightly recently, but enough to let the old instructions fail
    Remove reference to extremely old Ubuntu 9.10, no one should use this at this point
    Remove reference to testing being done with MPICH preferentially

**Comment by ipelupessy** [comment]
can you check this @rieder ?

**Comment by rieder** [comment]
Will do.

**Comment by rieder** [comment]
It looks like the docs page on amusecode.org hasn't been re-generated after this...

**Comment by ipelupessy** [comment]
no, this was done by the buildbot, but its down..

**Comment by ipelupessy** [comment]
btw where does https://amuse.readthedocs.io/ come from?

**Comment by rieder** [comment]
Not sure where that comes from, though it seems to be directly linked to https://github.com/amusecode/amuse/tree/master/doc <https://github.com/amusecode/amuse/tree/master/doc>. 
I'll check. It could be a useful page for hosting the docs...

**Comment by rieder** [comment]
I found a link to this page in an email from 2016, so it's been around for a while at least. Maybe @arjenve registered it? I guess it could be linked to the info at amusecode email address so we can hopefully find out more soon.

**Pull request merged**
