### PR TITLE
Update from Adrian Hamers (30 nov 2017)

### PR DESCRIPTION
**Pull request by maxwelltsai**

### CODE REVIEW

**Comment by ipelupessy** [comment]
can you remove the .DS_Store file?

**Comment by maxwelltsai** [comment]
@ipelupessy Done! .DS_Store file removed.

**Comment by ipelupessy** [comment]
I have tested it, it gives some "the corrector convergence test failed repeatedly or with |h| = hmin" warnings (errors?), but passes

**Comment by ipelupessy** [comment]
small comment @maxwelltsai : I would push the changes to an aptly named branch in your fork next time (instead to master)

**Pull request merged**
