### PR TITLE
Add installation docs for virtualenv-based installations

### PR DESCRIPTION
**Pull request by rieder**
This adds documentation for installing AMUSE in a Python virtual environment.
I've created the documentation for both Python2 and Python3, and for macOS and Ubuntu. 
I have tested these instructions on the most recent versions, but they should work (with perhaps minor modification) on older versions as well.

Please make sure this pull request is squash-merged when/if accepted, as commits to this branch include somewhat annoying merge and reversal commits...

### CODE REVIEW

**Comment by ipelupessy** [comment]
great! its a minor point but the naming of other documentation files are as .txt - also: do they need to be included in an index.txt?? (maybe a seperate page "install in virtualenv")?

**Comment by rieder** [comment]
Regarding naming: maybe it's best to rename all documentation files to .rst? That way, they show up as rst-formatted in editors (on github and in syntax-aware editors), which is nice... It doesn't matter for anything else, the extension is ignored in making the web documentation.

And yes, they'll need to be included in the index. I'll look into that tomorrow or so. A separate 'install in virtualenv' seems sood for now, but I think the documentation as a whole needs some refactoring to make it more accessible (and less out-of-date). I'll see if I can work on a proposal/pull request for that.

**Comment by ipelupessy** [comment]
ok, leave the files as rst for now, and maybe a seperate issue for the renaming of the other txt files? I would like @arjenve to comment, since he made the files txt...

**Comment by rieder** [comment]
Sure, renaming to rst would be a separate thing.

**Comment by rieder** [comment]
Is this one also OK to merge?

**Comment by ipelupessy** [comment]
I think the install index was not yet updated? also: its not building on the buildbot, so also the website does not get updated, will send you the link seperately...

**Comment by ipelupessy** [comment]
previous comment @rieder

**Comment by rieder** [comment]
You're right, hasn't been added yet. Looks like some restructuring of the documentation will need to be done before it makes sense to add these files there though (they essentially merge the installing of prerequisites and AMUSE into one). 
But I'll get on it (either next week or late August). I'll incorporate #235 and #240 as well.

**Comment by ipelupessy** [comment]
ok, also, see #266

**Comment by nluetzge** [comment]
Stupid question but where do I find this new documentation now? I don't think its on the amusecode website or I'm blind...

**Comment by rieder** [comment]
Hi @nluetzge,
Not a stupid question - these instructions don't seem to show up in the directory! This needs updating.
You can find them by manually using the path from the files in this PR only... 
E.g. for Python 2 on High Sierra: http://www.amusecode.org/doc/install/install-macos-highsierra-virtualenv-python2.html
Please note that these instructions are a bit out of date with the recent updates we've been working on.
A more recently updated set of instructions is on the wiki of my Amuse fork:
https://github.com/rieder/amuse/wiki/Installation-on-macOS-with-Python2 (for Python 2)
https://github.com/rieder/amuse/wiki/Installation-on-macOS-with-Python3 (for Python 3)

Note that the only difference between OSes is the installation of prerequisite libraries.

**Comment by nluetzge** [comment]
Awesome thanks @rieder ! I also just sent you an email 😆

**Pull request merged**
