### PR TITLE
Add mapper, a helper tool for making 2D maps from SPH particles.

### PR DESCRIPTION
**Pull request by rieder**
Makes life easier compared to directly using FiMap.
Plan is to expand this mapper to also use it with Fresco and to add a plotting tool separately.

### CODE REVIEW

**Comment by rieder** [comment]
@ipelupessy any thoughts?

**Comment by ipelupessy** [comment]
could be good idea... you may need to add an example for the usage (and maybe some doc string.) though..hard to see how to use it..

**Comment by ipelupessy** [comment]
btw, I think we are using ascii encoding for the source?

**Comment by rieder** [comment]
> could be good idea... you may need to add an example for the usage (and maybe some doc string.) though..hard to see how to use it..

yeah, use case will come in my plotting tool (see https://gist.github.com/rieder/abe1773776a9bb08503e06723d48ca66 for now). I found it better to separate these than have them in one big file.

**Comment by rieder** [comment]
I'm still working on it, syntax will probably change as I add `@property` decorators and such.

**Comment by rieder** [comment]
I simplified it and added a use case example. Still more to be done.

**Comment by rieder** [comment]
I've added (a simplified version of) plot_hydro, which uses mapper.
This seems to work well, but I'm not sure if it is "ready to merge" yet.

**Comment by rieder** [comment]
> hmm, would check your branches and remotes...

I can't see anything wrong. This is part of the right PR and all.

**Comment by ipelupessy** [comment]
ready for merge?

**Comment by rieder** [comment]
Almost. I’ve been using it but I need to add a nice example.

**Comment by ipelupessy** [comment]
suggest merge

**Comment by rieder** [comment]
It's good enough, merging!

**Pull request merged**
