### PR TITLE
bug in seba_time after recall_memory_one_step in SeBa interface

### PR DESCRIPTION
**Pull request by silviatoonen**
Do other stellar evolution codes have the same bug?

### CODE REVIEW

**Comment by rieder** [comment]
What does this do? It only seems to calculate seba_time, which is then not used anywhere...

**Comment by rieder** [comment]
I'm trying to find that issue, but I can't find it. Did we just discuss it in person?

**Comment by silviatoonen** [comment]
Hi Steven,
I reported it in the SeBa github and amuse github as a suggested change and added simon and you to it, I've also emailed about it and we chatted about it :)
Cheers Silvia


---------------------------------------------------------------------
Dr. Silvia Toonen
Assistant professor
Anton Pannekoek Institute
University of Amsterdam
Email:  ***@***.******@***.***>
***@***.******@***.***> will soon be deactivated.
Website: https://staff.fnwi.uva.nl/s.g.m.toonen/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaff.fnwi.uva.nl%2Fs.g.m.toonen%2F&data=04%7C01%7Cservicedesk-icts%40uva.nl%7Ce2bdbbd0a70043e9f36f08d8ccef8185%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637484676327089939%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=89YxQBjtPoJ%2BC3gAfS9IC6HGNPTNQPeMg47HQL0UMoo%3D&reserved=0>
---------------------------------------------------------------------
________________________________

**Comment by rieder** [comment]
Ah I see it now - it was already closed there! https://github.com/amusecode/SeBa/issues/18

**Review by rieder — APPROVED** [review]

**Pull request merged**
