### PR TITLE
Patch logging

### PR DESCRIPTION
**Pull request by rieder**
Attempt at implementing #362 (work very much in progress)

### CODE REVIEW

**Comment by ipelupessy** [comment]
good idea! following the "when to use logging" bit in https://docs.python.org/2/howto/logging.html
suggests keeping prints in the examples, and using logging/ warnings in the framework code
for things that report normal operation 

I think if there are obvious debug comments, you can also just comment them out...

**Comment by rieder** [comment]
I agree, in examples using "print" would be preferable. Modules should use logging.
Especially multiples and encounters will require some work...

**Comment by rieder** [comment]
What should be done with "verbose" user settings?
It would make sense to me to get rid of these entirely when we're using logging instead of printing.

**Comment by rieder** [comment]
i.e. the "verbose=True" option in Bridge() etc.

**Comment by ipelupessy** [comment]
I think the verbose option implies that you have control over the output of every instance, so you could make a logger at init:
```
class A(object):
  def __init__(self, verbose=False):
    self.l=logging.getLogger(str(self))
    if verbose:
        self.l.setLevel(logging.DEBUG)  
```

**Comment by rieder** [comment]
Yes, that would make sense.

**Comment by rieder** [comment]
(I did not yet apply this to the latest commit)

**Comment by ipelupessy** [comment]
many conflicts...also: what is the scope of the PR? I think breaking up and doing PR with partial replacement is an option..

**Comment by ipelupessy** [comment]
in view of the conflicts and comments this needs to be redone carefully, closing

**Pull request closed without merging**
