### PR TITLE
Mher/style fixes 1

### PR DESCRIPTION
**Pull request by mherkazandjian**
Hi,

I did major style fixes for the scripts under examples/application. 
The changes raise the ``pylint`` score from ``-4.01/10`` to ``+4.13/10``.
pylint also complains about some other code quality issues, but pep8 compatibility
is close to ideal now.
  
I also included the encoding (just for completeness) and the __future__ print to
enabled python3 compatibility.

### CODE REVIEW

**Comment by mherkazandjian** [comment]
hi @rieder ,
please have a look at the changes and let me know if you have any comments if you have time.
These are just style fixes so i suppose the tests scripts execution is not altered. (i didn't test that though)

**Comment by rieder** [comment]
Hi Mher,
Could you check if you’ve pulled the latest revision of Amuse? I just merged my own changes to the same example files earlier today, with the same intent. Some of the changes I see in your files seem to revert changes I made, and I see a few other changes I deliberately didn’t make. And definitely the pylint score is higher after my merger than before ;).
I will comment in more detail later. 
Steven

**Comment by mherkazandjian** [comment]
yes you are right. I reverted some of your changes since i got merge conflicts when i was testing to merge
onto master locally before pushing. sorry about that. i'll do another round tomorrow revert the reverted 
changes and make the script more compliant with pylint.

**Comment by mherkazandjian** [comment]
Hi @rieder 

i improved on the changes you did and kept the changes were you fixed a typo (e.g. the plumber -> Plummer ). There were several violations of the pep8 rule https://www.python.org/dev/peps/pep-0008/#other-recommendations
I also fixed serveral issues related to the order of the imports.
The overall pylint scrore is now 5.80 compared to 4.87 on the master branch.
here is the comparison also for the individual files
image

**Comment by ipelupessy** [comment]
these and other style changes are somewhat discouraged, so closing

**Pull request closed without merging**
