### PR TITLE
fix syntax of galaxia interface

### PR DESCRIPTION
**Pull request by rieder**
Fix numerous code style problems (indentation, imports, spaces). No functional change.

### CODE REVIEW

**Comment by ipelupessy** [comment]
I think the new version has a problem with the indentation of multiline line function arguments, ie:
```
   function.addParameter('x', dtype='float64', direction=function.IN
                            , description="x position",unit=units.kpc)
```
is transformed to:
```
   function.addParameter('x', dtype='float64', direction=function.IN
, description="x position",unit=units.kpc)
```
instead of
```
   function.addParameter('x', dtype='float64', direction=function.IN,
                                            description="x position",unit=units.kpc)
```

**Comment by ipelupessy** [comment]
please also remember that these kind of changes basically reset the file history (for e.g. blame)...

**Comment by ipelupessy** [comment]
ok, discard my earlier comment on the indent

**Comment by ipelupessy** [comment]
it was just the github viewer..

**Comment by ipelupessy** [comment]
or to be more precise: me misreading it...

**Comment by rieder** [comment]
> please also remember that these kind of changes basically reset the file history (for e.g. blame)...

Yes, this shouldn't be done too often, but sometimes it's necessary :).
The file history can still be retrieved, and it's exactly the reason why this change is specifically only targeting syntax changes.

**Comment by ipelupessy** [comment]
yea, in this case probably ok, but you can verify for yourself that the
[blame](https://github.com/amusecode/amuse/blame/e192c718f9de9b98d5113c3eeb46e3e301cbe38f/src/amuse/community/galaxia/interface.py) is not exactly informative now;-)

**Comment by rieder** [comment]
Not in master, but you could easily go back to an earlier version (e.g. right before this merge, https://github.com/amusecode/amuse/tree/d597c0f0935b5afdd4d5a45b1b90619436b33e56) and check changes there.
Mucking up git blame a bit can't in itself be a reason not to make changes ;-).

**Comment by rieder** [comment]
Not that blame on this interface would be that much more informative then...

**Pull request merged**
