### PR TITLE
remove old kickoff presentation pdfs

### PR DESCRIPTION
**Pull request by ipelupessy**
I guess there is no real reason to have these in the repository..if we want to have them its maybe better to move them somewhere else?

### CODE REVIEW

**Comment by rieder** [comment]
Yeah I agree.

**Comment by ipelupessy** [comment]
its kind of nice to have it somewhere for historical reasons (I recently showed some of the old slides to illustrate where we came from..)..can we host files on the website?

**Comment by ipelupessy** [comment]
otherwise the sandbox?

**Comment by rieder** [comment]
Either the website or the sandbox would be a better place. I think sandbox is the best place - the website should preferably include more up to date things.

**Comment by ipelupessy** [comment]
done

**Pull request merged**
