### PR TITLE
make all makefiles use amusifier

### PR DESCRIPTION
**Pull request by ipelupessy**
fixes some inconsistent build issues

### CODE REVIEW

**Comment by ipelupessy** [comment]
I need to know if I got all references and whether packages still work..

**Comment by rieder** [comment]
Codes are building fine for me - both with 'make X.code' and in the code directory itself (using the "pip install -e ." method to install AMUSE).

**Comment by ipelupessy** [comment]
oops, they should have the same (they have = instead of =? so missed them)

**Comment by rieder** [comment]
> oops, they should have the same (they have = instead of =? so missed them)

Ok, I changed them.

**Comment by ipelupessy** [comment]
thanks!

**Comment by rieder** [comment]
I'm happy for this to be merged.

**Comment by ipelupessy** [comment]
waiting whether @MJCWilhelm has any comments (should solve his problems..)

**Comment by MJCWilhelm** [comment]
With this change the './configure make' only works partially; only asterisk, gadget2, galactics, higpus and mameclot are successfully built. The others I can't build through 'make code.code', although some can be built in their community directories (tested this with bse, which didn't build, and ph4 and fi, which did). Also, building gadget2 (one of the ones that did build at first) in its directory did work.

I still suspect that it has something to do with how amuse runs on the strw pc's (using 'mpiexec $AMUSE_DIR/amuse.sh' instead of just 'python'). My errors are that amuse can't be imported, which is exactly what happens when you try to import amuse in a normal python session on these pc's.

**Comment by ipelupessy** [comment]
ok, did you follow either (which?) of the procedures I lined out in #587? (setting environment variables or using virtualenv & pip install -e . - the environment variables are needed because otherwise python will not be able to import and the amusifier script needs to be in the PATH, if you use the pip development install, pip takes care of this (while linking to the development dir instead installing the files))

**Comment by MJCWilhelm** [comment]
I did use a virtual environment, but built amuse using the old './configure / make' method, since the pip version doesn't work on the strw machines. Amuse does build, but it gives errors when trying to run (even freezing when trying 'python script.py'). I did see that amusifier was added the venv's bin, which it wasn't before.

**Comment by ipelupessy** [comment]
ok, in that case you have to set the environment variables!

**Comment by MJCWilhelm** [comment]
I set the environment variables you mentioned and then both the main folder and code folder makefiles work. 

With this change, rebuilding codes does become a bit annoying when using the old installation method (having to set two extra environment variables). Is there a good way to append to them automatically? Perhaps the makefile can check whether they are in the (PYTHON)PATH?

**Comment by rieder** [comment]
I wouldn't recommend the old method anymore. I'd much prefer fixing the new method for where it doesn't work currently to messing with environment variables.

**Comment by ipelupessy** [comment]
ok, great, I take it it is working then!

what I usually do is putting the environment variables (or virtualenv sourcing and other stuff (such as selecting the mpi flavour)) in a file named setdev in the root of a project folder..its always a matter of sourcing a single file then...note that from the viewpoint of amuse whichever method you use for setting up your environment should work (whether you do it fully manually, or partially or wholly managed by virtualenv or other tools..)..if something seemed to work before w/o configuration its was essentialy a happy coincidence;-)

**Pull request merged**
