### PR TITLE
Add initial Travis CI configuration

### LINKED ISSUE #241: Add Travis CI testing
Following up on https://github.com/amusecode/amuse/issues/153#issuecomment-399291984, let's get Travis CI going.

For reference: @rieder's branch contains a [Travis file](https://github.com/rieder/amuse/blob/cover/.travis.yml) for which I don't see any objections to merging.

We can build on it from there to include coverage of a build matrix containing:
- macOS
- probably also Python 3.5/3.6
- perhaps some contributor code tests (though I heard they take very long, so maybe not test everything on all platforms; the CUDA codes will not work anyway)
- maybe a code coverage tool for amuse_core

### PR DESCRIPTION
**Pull request by egpbos**
I rebased out a few unrelated commits from @rieder's version of the file, but the two files added here are straight from @rieder's branch.

Fixes #241

### CODE REVIEW

**Comment by ipelupessy** [comment]
I think the readme badge points to stevens' travis??

**Comment by egpbos** [comment]
Sharp @ipelupessy, fixed now :)

**Comment by egpbos** [comment]
The build now also actually completes. I removed the failing matplotlib test, which was probably the reason @rieder modified the plot test in his branch, but I think this deserves a separate issue.

**Comment by rieder** [comment]
Thanks @egpbos! For the matplotlib tests, probably it would be good to add a 'matplotlibrc' file to specify a backend without need for a screen (like "Agg").

**Comment by ipelupessy** [comment]
merge or wait for the matplotlib fix? btw what was the reason to exclude test_grid_implementation?

**Comment by rieder** [comment]
The grid_implementation test takes forever for some reason... It simply doesn't run.

**Comment by ipelupessy** [comment]
ok, that needs a seperate issue, as well as the matplotlib thingy, merging

**Pull request merged**
