### PR TITLE
Patch rebound delete

### PR DESCRIPTION
**Pull request by rieder**
Fixes for bug #105. Only still fails on the final part of test3, can't figure that out yet (help would be appreciated). But deleting particles this way seems to work correctly, and much faster than previous method.

### CODE REVIEW

**Comment by rieder** [comment]
(more testing needed)

**Comment by rieder** [comment]
All tests run without problems, but I need to re-add the detection of massless particles after the initial commit.

**Comment by ipelupessy** [comment]
should it wait for that (detection of massless particles after the initial commit)?

**Comment by arjenve** [comment]
I know it is being used (but maybe not unit tested). So it is essential....

**Comment by rieder** [comment]
I think fixing this memory leak is more important than support for non-active particles. 
But please wait a little while longer, I'm working on it this week so I hope to get it done soon. 
If I can't get it done this week, please merge this one first and I'll work on re-adding massless particle resorting afterwards.

**Comment by rieder** [comment]
@arjenve am I right in thinking that in the ordering of particles the only important issue is that massless particles should be last (and that N_active == number of non-massless particles)?

**Comment by arjenve** [comment]
Yes correct, this is the only reason we need to sort....

**Comment by rieder** [comment]
Ok, great! Thanks!

**Comment by ipelupessy** [comment]
have you tested this last bit (the massless particles) , not sure it is covered by the tests...

**Comment by rieder** [comment]
It's not covered by the tests, I'm not sure how to test it in a "nosetests" way. (This wasn't covered by tests before either...)
However, I have done this manually, by manually printing N_active value and particle attributes after changing particle masses, and by comparing execution time between a simulation with mostly massless particles and one with the same N but no massless particles.

**Comment by rieder** [comment]
This fixes #105

**Comment by rieder** [comment]
Hi,

Is there a way to prevent particles from ending up more than once in a particleset?

Currently, I get this:
p = Particle()
ps = Particles()
ps.add_particle(p)
ps.add_particle(p)
print ps
                 key
                   -
====================
11252531812499082495
11252531812499082495
====================

and I hope to get a set where each key is unique...

Steven

**Comment by spzwart** [comment]
what about the following:

for pi in p:
    if pi not in ps:
         ps.add_particle(pi)

Simon

**Comment by rieder** [comment]
Thanks Simon, that would work.

Also, oops, this should have been sent to the Amuse list, not to Github...

**Pull request merged**
