### PR TITLE
Add "amuse-core" package which installs python-only bits of AMUSE

### PR DESCRIPTION
**Pull request by rieder**
An attempt at fixing #412, splits of amuse-core package from amuse-framework.

Work in progress, overlapping files need to be removed from amuse-framework to prevent conflicts.

### CODE REVIEW

**Comment by rieder** [comment]
This will be much easier once we only support one Python version, so this is for after 13.0 is released.

**Comment by ipelupessy** [comment]
amuse-framework with dependency on amuse-core?

**Comment by rieder** [comment]
yes

**Comment by ipelupessy** [comment]
ok, don't worry about the commits, I am adding something but merged master first..

**Comment by ipelupessy** [comment]
there is now a seperate core install mode which should handle core installs properly (I don't think it actually changes anything, but now we can add things if we want)

**Comment by ipelupessy** [comment]
I have tried this together with #501 (it needs something to prevent the config error), and it installs and allows you to do *something* (importing units)

**Comment by ipelupessy** [comment]
I have tried this together with #501 (it needs something to prevent the config error), and it installs and allows you to do *something* (importing units)..its fairly annoying though that if you make amuse-core a requirement for amuse-framework a purely local install does not work..

**Comment by ipelupessy** [comment]
ok, this is fixable with --find-links option to pip, next:
(development install)
```
pip install -e . 
```
does not work casue it cannot find the config
(I am trying out an amuse-framework edit which I didn;t commit yet)

**Comment by ipelupessy** [comment]
I have tried to make changes to amuse-framework, it has the above config problem (which is fixable), but more seriously, the uninstall does not work properly (pip uninstall of amuse-framework removes core components) ---this indicates something seriously wrong with the way we implement this.l..

**Comment by rieder** [comment]
Hmm, yes, that would be a problem... Wondering if this is the same as what I found in #424? I was never really sure about that one...

**Comment by ipelupessy** [comment]
How was #424 resolved? I don't know how the removal of a package works..

**Comment by rieder** [comment]
It wasn't resolved (reopened now), but after updating manifest I couldn't reproduce it... Also didn't test it all that much.

**Comment by rieder** [comment]
Relevant documentation for packaging: https://packaging.python.org/guides/packaging-namespace-packages/
I don't think we're doing it right currently...

**Comment by ipelupessy** [comment]
hmm..on the other hand, the problem we encunter doesn't look like anything that is described as failure modes in the link...

**Comment by ipelupessy** [comment]
I think this is currently low priority, maybe defer? @rieder

**Comment by ipelupessy** [comment]
close due to low priority

**Pull request closed without merging**
