### PR TITLE
attempt at fixing incompatibility in io for python3 (github issue #190)

### PR DESCRIPTION
**Pull request by ipelupessy**
this is work in progress for issue #190

### CODE REVIEW

**Comment by rieder** [comment]
To test this, we need
- a savefile from amuse-py2
- a savefile from amuse-py3
- a savefile from amuse-py3-with-fix

All of these savefiles should be readable in amuse-py2 and amuse-py3 with this fix applied.

**Comment by rieder** [comment]
Doesn't work yet:
```
(Amuse12-py3-iofix) rieder@Wollebasje TestAmuseSavefiles $ python TestReadFile.py 
Traceback (most recent call last):
  File "TestReadFile.py", line 8, in <module>
    "amuse"
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/base.py", line 99, in read_set_from_file
    return processor.load()
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store.py", line 45, in load
    processor, result = self.load_base()
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store.py", line 86, in load_base
    result = processor.load()
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store_v1.py", line 718, in load
    return self.load_particles(self.particles_group())
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store_v1.py", line 777, in load_particles
    return self.load_container(container_group, 'particles')
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store_v1.py", line 790, in load_container
    container = self.load_from_group(group, default_type)
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store_v1.py", line 767, in load_from_group
    return self.load_particles_from_group(group)
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store_v1.py", line 732, in load_particles_from_group
    class_of_the_particles = unpickle_from_string(group.attrs["class_of_the_particles"])
  File "/Users/rieder/Env/Amuse12-py3-iofix/lib/python3.6/site-packages/amuse/io/store_v1.py", line 29, in unpickle_from_string
    return pickle.loads(value.tostring())
AttributeError: 'bytes' object has no attribute 'tostring'
```

[TestFilesForIOBug.zip](https://github.com/amusecode/amuse/files/3401781/TestFilesForIOBug.zip)

**Comment by rieder** [comment]
Reading any py3-saved file (with or without this fix) results in `ValueError: unsupported pickle protocol: 3`

**Comment by ipelupessy** [comment]
fixed now, but I want to check for grids...

**Comment by rieder** [comment]
OK, I will not merge yet...

**Comment by ipelupessy** [comment]
seems to work ok now

**Comment by ipelupessy** [comment]
the only thing you cannot is reading old python 3 with (old or new) python 2, new python 3 can be read by new python 2

**Comment by rieder** [comment]
I think that's completely acceptable. A workaround can always be to read the file and write it to a new file with Python3 in those cases.

**Pull request merged**
