### PR TITLE
Prepare packages for v12

### PR DESCRIPTION
**Pull request by rieder**
work in progress

### CODE REVIEW

**Comment by ipelupessy** [comment]
I would centralize the version bookkeeping (file in support?)

**Comment by rieder** [comment]
indeed (see #437)

**Comment by rieder** [comment]
file(s) in support could work (support/version/MAJOR, MINOR, MICRO, PRE, POST)?

**Comment by ipelupessy** [comment]
just a version.py would do? With a manually updated version first..there is code to generate version strings automatically, but I have not found them to be very satisfying

**Comment by rieder** [comment]
Sounds good. I’ll do that.

**Comment by rieder** [comment]
I think it's OK now.

**Pull request merged**
