### PR TITLE
Packages tryout

### PR DESCRIPTION
**Pull request by ipelupessy**
this is just for testing atm

### CODE REVIEW

**Comment by rieder** [comment]
amuse-sse should depend on amuse-framework being installed.

**Comment by rieder** [comment]
do we call it amuse-framework? amuse can then be a meta-package that does a full installation.

**Comment by ipelupessy** [comment]
yea, I didn't pay attention to names and/or dependencies yet...(your previous proposal was ok)
I think all codes and packages after the framework can use the same support/setup_codes.py so it may be an idea to move this (or join if possible) to the root support...the packages will need different setup.py (but they still can be simplified /slimmed down further...)

**Comment by ipelupessy** [comment]
btw have you seen #391 ??

**Comment by ipelupessy** [comment]
I think we can remove distributed from the framework package (since also it is not working atm)
also, I think it may be nice to add a function that reports the available codes for an installation...

**Comment by rieder** [comment]
Yes to both. 

By the way, why is distributed not working? Is there an issue for this?

**Comment by ipelupessy** [comment]
there is a failure to communicate with a Pilot process (when using ssh starting Pilot on another machine) - I am checking whether I misconfigured something, but I think not...(will make a proper issue otherwise)

**Comment by ipelupessy** [comment]
i have made some changes (#395)..these are merged here too, simplifies the package directories...may neeed some testing

**Comment by rieder** [comment]
I'm testing this implementation now for the Phantom interface (https://github.com/rieder/amuse/tree/patch-add-phantom). Seems to work quite well. I can now install amuse-phantom with only amuse-framework as requirement, saving a lot of time on compiling packages that shouldn't need recompiling when I change a small thing in the Phantom interface.
Only "issue" is amuse.lab - that won't work until all amuse 'base' community packages are installed. But I don't think that is a problem. It can be solved by installing a meta-package 'amuse' which depends on all of these.
I think this method is the way forward for installing AMUSE.

**Comment by ipelupessy** [comment]
I agree;-) The only task left is maybe generating all the subpackages - I think this could be done semi-automatically (and add this to the 'amusifier' script #397 ??)

**Comment by rieder** [comment]
Let's get this done when I visit Leiden after easter?

**Comment by ipelupessy** [comment]
sounds good..

**Comment by rieder** [comment]
We may want to rethink the "DOWNLOAD_ONLY" codes as well in this process. 
If these are separate packages, this flag makes no sense anymore. Probably we should exclude them from the "amuse" meta-package instead, and not include them in lab.py?

**Comment by ipelupessy** [comment]
think lab should detect which codes are available...

**Comment by rieder** [comment]
Yes that would be a good option. If a code is not installed (i.e. ImportError is raised), we could show a message with installation instructions (e.g. 'pip install amuse-${codename}).

**Comment by ipelupessy** [comment]
for the imports in lab: something like this is actually in codes.py... (looks like *old* code)

**Comment by rieder** [comment]
That file was last touched 9 years ago, so old indeed!
But yes, the general idea of that file seems like a good one to implement once again. 
I'll have a go at it.

**Comment by rieder** [comment]
Maybe we should have a go at #132 while we're at this... 
And perhaps also a more unified way of naming codes/interfaces (currently it's anyone's guess which letters are capitalised). E.g.: hermite0/HermiteInterface -> hermite/hermiteInterface; phiGRAPE/PhiGRAPEInterface -> phigrape/phigrapeInterface
(move to consistent names and allowing the current names to work with a deprecation warning)

**Comment by rieder** [comment]
I can't figure out how to do a "from X import Y" using importlib and import_module... @ipelupessy do you know how this could work?

**Comment by ipelupessy** [comment]
you mean:
```
def get_code_interface(code, classes):
  module=importlib.import_module("amuse.community."+code+".interface)
  for class in classes:  
    globals[class]=getattr(module, class)
```
called as:
```
get_code_interface("fi", ["FiInterface", "Fi"])
```
???

**Comment by ipelupessy** [comment]
btw, i have changed some things simplifying the setup.pys..hopefully it didn't break anything (it shouldn't..)

**Comment by rieder** [comment]
> you mean:
> 
> ```
> def get_code_interface(code, classes):
>   module=importlib.import_module("amuse.community."+code+".interface)
>   for class in classes:  
>     globals[class]=getattr(module, class)
> ```
> called as:
> 
> ```
> get_code_interface("fi", ["FiInterface", "Fi"])
> ```
> ???

Ah yes, that looks good.

**Comment by rieder** [comment]
> btw, i have changed some things simplifying the setup.pys..hopefully it didn't break anything (it shouldn't..)

I'll check (but first impression is good - much cleaner now!)

**Comment by ipelupessy** [comment]
its not working yet (minor import problem)..will fix it in a bit, catching train...

**Comment by ipelupessy** [comment]
should be fixed now..

**Comment by ipelupessy** [comment]
still broken..

**Pull request merged**
